# -*- coding: utf-8 -*-
"""Kalys-Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jjZEmUvxAM5DKRZ1HAY_3woEJsNVkL8-
"""

# Commented out IPython magic to ensure Python compatibility.
# %pylab inline

url = 'https://data.boston.gov/api/3/action/datastore_search_sql'

sql = '''
SELECT "DISTRICT",
       "OCCURRED_ON_DATE",
       "SHOOTING",
       "OFFENSE_DESCRIPTION"
FROM "b973d8cb-eeb2-4e7e-99da-c92938efc9c0"
WHERE CAST("SHOOTING" AS INT)=1
'''

import requests, urllib

final_url = url +"?sql="+urllib.parse.quote(sql)

final_url

rows = requests.get(final_url).json()

rows.keys()

shootings = rows['result']['records']

shootings[0]

shootings[5:10]

import pandas as pd

df = pd.DataFrame(shootings)

df['OCCURRED_ON_DATE'] = pd.to_datetime(df['OCCURRED_ON_DATE'])

df['HOUR'] = df["OCCURRED_ON_DATE"].dt.hour

df['DAY_OF_WEEK'] = df["OCCURRED_ON_DATE"].dt.dayofweek

weekly_districts = df.groupby(['DAY_OF_WEEK', "DISTRICT"]).size().reset_index(name='COUNT')

weekly_districts_pivot = weekly_districts.pivot(index='DAY_OF_WEEK', columns='DISTRICT', values='COUNT').fillna(0)

weekly_districts_pivot

weekday_hour_count = df.groupby(['HOUR', "DAY_OF_WEEK"]).size().reset_index(name='COUNT')

weekly_pivot = weekday_hour_count.pivot(index='DAY_OF_WEEK', columns='HOUR', values='COUNT').fillna(0)

weekly_pivot



"""A1	Downtown / North End / Beacon Hill
A15	Charlestown
A7	East Boston
B2	Roxbury / Mission Hill
B3	Mattapan
C11	Dorchester
C6	South Boston
D14	Brighton / Allston
D4	South End / Back Bay / Fenway
E13	Jamaica Plain
E18	Hyde Park
E5	West Roxbury / Roslindale

"""

